name: Update NitroType Leaderboards

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours at minute 0 (e.g. 00:00, 06:00, 12:00, 18:00)
  workflow_dispatch:        # Allows manual triggering from the GitHub Actions tab

jobs:
  update-leaderboards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests pandas

      - name: Run Leaderboard Script
        run: |
          python nitrotype_leaderboard.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          # Only commit if there are changes; prevent error exit if nothing changed
          git diff-index --quiet HEAD || git commit -m "Auto update leaderboard at $(date)"
      
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
